import { Container, Heading, Link as ChakraLink } from "@chakra-ui/react";
import { paths } from "@utils/paths";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import Link from "next/link";
import { ReactElement, ReactNode } from "react";
import { Logout } from "./Logout/Logout";

type Props = {
  children: ReactNode;
};

export const ProtectedLayout = ({ children }: Props): ReactElement => {
  const { t } = useTranslation("common", { keyPrefix: "ProtectedLayout" });

  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Container display="flex" flexDirection="column">
        <Link href={paths.index()} passHref>
          <ChakraLink>
            <Heading>{t("title")}</Heading>
          </ChakraLink>
        </Link>
        <Logout />
        {children}
      </Container>
    </>
  );
};
