import {
  Box,
  Container,
  Heading,
  HStack,
  Link as ChakraLink,
  VStack,
} from "@chakra-ui/react";
import { paths } from "@utils/paths";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import Link from "next/link";
import { ReactElement, ReactNode } from "react";
import { Logout } from "./Logout/Logout";
import { Profile } from "./Profile/Profile";

type Props = {
  children: ReactNode;
};

export const ProtectedLayout = ({ children }: Props): ReactElement => {
  const { t } = useTranslation("common", { keyPrefix: "ProtectedLayout" });

  return (
    <>
      <Head>
        <title>{t("title")}</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Box
        backgroundColor="gray.50"
        h="100vh"
        left={0}
        position="absolute"
        top={0}
        w="100vw"
        zIndex={-1}
      />
      <VStack w="full">
        <HStack
          backgroundColor="white"
          gap={1}
          justifyContent="space-between"
          px={6}
          py={4}
          w="full"
        >
          <HStack gap={1}>
            <Link href={paths.index()} passHref>
              <ChakraLink>
                <Heading>{t("title")}</Heading>
              </ChakraLink>
            </Link>
            <Link href={paths.invites()} passHref>
              <ChakraLink>{t("invites")}</ChakraLink>
            </Link>
          </HStack>
          <HStack>
            <Profile />
            <Logout />
          </HStack>
        </HStack>
        <Container display="flex" flexDirection="column" maxW="container.xl">
          {children}
        </Container>
      </VStack>
    </>
  );
};
