import { Logout } from "@modules/Logout/Logout";
import { Rooms } from "@modules/Rooms/Rooms";
import { withAuthorization } from "@services/withAuthorization";
import { withTranslations } from "@services/withTranslations";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>
        <Logout />
        <Rooms />
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = withAuthorization(
  withTranslations()
);

export default Home;
