import { Login } from "@modules/Login/Login";
import { withPublic } from "@services/withPublic";
import { withTranslations } from "@services/withTranslations";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Login />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = withPublic(
  withTranslations()
);

export default SignIn;
